services:
  db:
    image: postgres:15
    container_name: job-tracker-db
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./app
    container_name: job-tracker-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jobtracker
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      BASE_URL: http://localhost:8080
      GOOGLE_CLIENT_ID: your_google_client_id
      GOOGLE_CLIENT_SECRET: your_google_client_secret
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: job-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  db_data:
